// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_tokens.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEmailToken = `-- name: ConsumeEmailToken :one
UPDATE email_tokens
SET used_at = NOW()
WHERE token = $1 
    AND used_at IS NULL 
    AND expires_at > NOW()
    AND purpose = $2
RETURNING user_id
`

type ConsumeEmailTokenParams struct {
	Token   string
	Purpose string
}

func (q *Queries) ConsumeEmailToken(ctx context.Context, arg ConsumeEmailTokenParams) (uuid.UUID, error) {
	row := q.db.QueryRowContext(ctx, consumeEmailToken, arg.Token, arg.Purpose)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const createEmailToken = `-- name: CreateEmailToken :one
INSERT INTO email_tokens(token, user_id, purpose, expires_at)
VALUES($1, $2, $3, $4)
RETURNING token, user_id, purpose, expires_at, used_at
`

type CreateEmailTokenParams struct {
	Token     string
	UserID    uuid.UUID
	Purpose   string
	ExpiresAt time.Time
}

func (q *Queries) CreateEmailToken(ctx context.Context, arg CreateEmailTokenParams) (EmailToken, error) {
	row := q.db.QueryRowContext(ctx, createEmailToken,
		arg.Token,
		arg.UserID,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var i EmailToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.Purpose,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
