// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countItemsForUser = `-- name: CountItemsForUser :one
SELECT COUNT(*)
FROM user_subscriptions AS u
INNER JOIN items AS i ON i.feed_id = u.feed_id
WHERE u.user_id = $1
`

// Total items across everything this user follows. Drives page count + range.
// No feeds join needed: we only count, and feed_id lives on both tables.
func (q *Queries) CountItemsForUser(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countItemsForUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO items(id, feed_id, guid, url, title, summary, author, published_at)
VALUES(gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(feed_id, guid)
DO NOTHING
`

type InsertItemParams struct {
	FeedID      uuid.UUID
	Guid        string
	Url         string
	Title       string
	Summary     sql.NullString
	Author      sql.NullString
	PublishedAt sql.NullTime
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Summary,
		arg.Author,
		arg.PublishedAt,
	)
	return err
}

const listItemsForUser = `-- name: ListItemsForUser :many
SELECT i.id, i.title, i.url, i.summary, i.image_url, i.published_at,
         f.title AS source_title, f.source_type
FROM user_subscriptions AS u
INNER JOIN feeds AS f ON f.id = u.feed_id
INNER JOIN items AS i ON i.feed_id = f.id
WHERE u.user_id = $1
ORDER BY i.fetched_at DESC
LIMIT $2 OFFSET $3
`

type ListItemsForUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

type ListItemsForUserRow struct {
	ID          uuid.UUID
	Title       string
	Url         string
	Summary     sql.NullString
	ImageUrl    sql.NullString
	PublishedAt sql.NullTime
	SourceTitle sql.NullString
	SourceType  string
}

func (q *Queries) ListItemsForUser(ctx context.Context, arg ListItemsForUserParams) ([]ListItemsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemsForUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsForUserRow
	for rows.Next() {
		var i ListItemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.Summary,
			&i.ImageUrl,
			&i.PublishedAt,
			&i.SourceTitle,
			&i.SourceType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
