// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: items.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const insertItem = `-- name: InsertItem :exec
INSERT INTO items(id, feed_id, guid, url, title, content, author, published_at)
VALUES(gen_random_uuid(), $1, $2, $3, $4, $5, $6, $7)
ON CONFLICT(feed_id, guid)
DO NOTHING
`

type InsertItemParams struct {
	FeedID      uuid.UUID
	Guid        string
	Url         string
	Title       string
	Content     sql.NullString
	Author      sql.NullString
	PublishedAt sql.NullTime
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.FeedID,
		arg.Guid,
		arg.Url,
		arg.Title,
		arg.Content,
		arg.Author,
		arg.PublishedAt,
	)
	return err
}
