// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EmailToken struct {
	Token     string
	UserID    uuid.UUID
	Purpose   string
	ExpiresAt time.Time
	UsedAt    sql.NullTime
}

type Feed struct {
	ID              uuid.UUID
	FeedUrl         string
	Title           sql.NullString
	SiteUrl         sql.NullString
	Etag            sql.NullString
	LastModified    sql.NullString
	LastFetchedAt   sql.NullTime
	LastFetchStatus sql.NullString
	LastFetchError  sql.NullString
	CreatedAt       time.Time
}

type Item struct {
	ID          uuid.UUID
	FeedID      uuid.UUID
	Guid        string
	Url         string
	Title       string
	Content     sql.NullString
	Author      sql.NullString
	PublishedAt sql.NullTime
	FetchedAt   time.Time
}

type ItemNotification struct {
	UserID     uuid.UUID
	ItemID     uuid.UUID
	NotifiedAt time.Time
}

type Session struct {
	Token     string
	UserID    uuid.UUID
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID              uuid.UUID
	Email           string
	HashedPassword  string
	EmailVerifiedAt sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type UserSubscription struct {
	UserID       uuid.UUID
	FeedID       uuid.UUID
	CustomTitle  sql.NullString
	SubscribedAt time.Time
}
