// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_subscriptions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUserSubscription = `-- name: CreateUserSubscription :exec
INSERT INTO user_subscriptions (user_id, feed_id, custom_title)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, feed_id) DO NOTHING
`

type CreateUserSubscriptionParams struct {
	UserID      uuid.UUID
	FeedID      uuid.UUID
	CustomTitle sql.NullString
}

func (q *Queries) CreateUserSubscription(ctx context.Context, arg CreateUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createUserSubscription, arg.UserID, arg.FeedID, arg.CustomTitle)
	return err
}

const deleteUserSubscription = `-- name: DeleteUserSubscription :exec
DELETE FROM user_subscriptions
WHERE user_id = $1
AND feed_id = $2
`

type DeleteUserSubscriptionParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteUserSubscription(ctx context.Context, arg DeleteUserSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserSubscription, arg.UserID, arg.FeedID)
	return err
}

const listUserSubscriptions = `-- name: ListUserSubscriptions :many
SELECT f.id AS feed_id, u.custom_title,  f.last_fetch_status 
FROM user_subscriptions AS u
INNER JOIN feeds AS f
ON u.feed_id = f.id
WHERE u.user_id = $1
ORDER BY u.subscribed_at DESC
`

type ListUserSubscriptionsRow struct {
	FeedID          uuid.UUID
	CustomTitle     sql.NullString
	LastFetchStatus sql.NullString
}

func (q *Queries) ListUserSubscriptions(ctx context.Context, userID uuid.UUID) ([]ListUserSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSubscriptionsRow
	for rows.Next() {
		var i ListUserSubscriptionsRow
		if err := rows.Scan(&i.FeedID, &i.CustomTitle, &i.LastFetchStatus); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
