// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EmailToken struct {
	Token     string
	UserID    pgtype.UUID
	Purpose   string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}

type Feed struct {
	ID              pgtype.UUID
	FeedUrl         string
	Title           pgtype.Text
	SiteUrl         pgtype.Text
	Etag            pgtype.Text
	LastModified    pgtype.Text
	LastFetchedAt   pgtype.Timestamptz
	LastFetchStatus pgtype.Text
	LastFetchError  pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type Item struct {
	ID          pgtype.UUID
	FeedID      pgtype.UUID
	Guid        string
	Url         string
	Title       string
	Content     pgtype.Text
	Author      pgtype.Text
	PublishedAt pgtype.Timestamptz
	FetchedAt   pgtype.Timestamptz
}

type ItemNotification struct {
	UserID     pgtype.UUID
	ItemID     pgtype.UUID
	NotifiedAt pgtype.Timestamptz
}

type Session struct {
	Token     string
	UserID    pgtype.UUID
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID              pgtype.UUID
	Email           string
	PasswordHash    string
	EmailVerifiedAt pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type UserSubscription struct {
	UserID       pgtype.UUID
	FeedID       pgtype.UUID
	CustomTitle  pgtype.Text
	SubscribedAt pgtype.Timestamptz
}
